query Beers {
    beers {
        id
        name
        description
        abv
        price
        size
        image {
            url
        }
        category {
            name
        }
    }
}
